channels:
    - conda-forge

dependencies:
    - arraylake >=0.14.0
    - cfgrib
    - dask
    - fsspec
    - herbie-data
    - s3fs
    - pydantic >2
    - xarray
    - pip:
      - modal
      - icechunk
