[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    "E", # pycodestyle
    "F", # Pyflakes
    "UP", # pyupgrade
    "B", # flake8-bugbear
    "SIM",     # flake8-simplify
    "I", # isort
    "RSE", # Raise
    "NPY", # numpy
    "RUF", # Ruff
]
ignore = [
    "UP032", # format in logger statements
]

# TODO: mypy improvements for these
[[tool.mypy.overrides]]
ignore_missing_imports = true
module=[
"cartopy.*",
"fsspec.*",
"herbie.*",
"pyproj.*",
"zarr.*",
]
