[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = [
    "UP032", # format in logger statements
]

# TODO: mypy improvements for these
[[tool.mypy.overrides]]
ignore_missing_imports = true
module=[
"cartopy.*",
"fsspec.*",
"herbie.*",
"pyproj.*",
"zarr.*",
]
