# Format
# ------
# [arbitrary_name]
# ## Three Herbie Parameters
# model = string
# product = string
# search = string
# ## Two Zarr store Parameters
# store = string  e.g. s3://my-bucket/store.zarr
# zarr_group = string e.g. "sfc/fcst"
# ## Schema
# chunks = {string: int}, integer chunk size for dimension
# renames = {str: str}, mapping from variable name in inventory to actual name when read with cfgrib


[job1]
model = "hrrr"
product = "sfc"
searches = [
  "(?:TMP|RH):2 m above ground|(?:GUST|DSWRF|PRATE):surface|TCDC:entire atmosphere",
]
store = "arraylake://earthmover-demos/hrrr"
zarr_group =  "solar/"
chunks = {x = 360, y = 120, time = 1, step = 19}
renames = {TMP="t2m", RH="r2", TCDC="tcc"}

# [job2]
# model = "hrrr"
# product = "sfc"
# store = "arraylake://earthmover-demos/hrrr-3"
# zarr_group =  "sfc/fcst/"
# search = d[":(?:DSWRF|PRATE|[UV]GRD):(?:surface|1000 mb):(?:anl|[0-9]* hour fcst)"
# chunks={x = 360, y = 120, time = 1, step = 19}

# TODO: This is unsupported currently
# [job3]
# model = "hrrr"
# product = "sfc"
# store = "arraylake://earthmover-demos/hrrr-3"
# zarr_group =  "sfc/rechunked/"
# searches = [
#   ":(?:DSWRF|PRATE|[UV]GRD):(?:surface|1000 mb):(?=\\banl|6|12|18\\b)",
# ]
# chunks = {x = 360, y = 120, time = 24, step = 1}
